- name: Create a folder
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item.name}}"
    password: admin123
    url: http://172.31.7.189:8080
    user: admin
  loop:
    - { name: "ci-pipelines" }


- name: include multi branch task file
  ansible.builtin.include_tasks: mbranch.yml
  loop:
    - { name: "cart" }