- name: Build job file from template
  ansible.builtin.template:
    src: folder.xml
    dest: /tmp/mbranch.yml


- name: Create a multibranch job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/mbranch.xml') }}"
    name: "{{item.name}}"
    password: admin123
    url: http://172.31.7.189:8080
    user: admin
  loop:
    - { name: "cart" }