- name: Build job file from template
  ansible.builtin.template:
    src: sbranch.xml
    dest: /tmp/sbranch.xml


- name: Create a singlebranch job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/sbranch.xml') }}"
    name: "terraform/{{item.name}}"
    password: admin123
    url: http://172.31.7.189:8080
    user: admin
